name: trekka
description: A travel_preferences planning app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0             # Gọi API
  flutter_bloc: ^9.1.1    # State Management
  equatable: ^2.0.7       # So sánh object
  get_it: ^9.1.1          # Dependency Injection
  dartz: ^0.10.1          # Functional programming
  go_router: ^17.0.0     # Điều hướng thông minh
  google_fonts: ^6.1.0    # Font chữ
  flutter_svg: ^2.0.9     # Hiển thị Logo SVG
  cupertino_icons: ^1.0.5 # Biểu tượng iOS
  shared_preferences: ^2.1.1 # Lưu trữ dữ liệu cục bộ

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/trekka_logo.png
    - assets/images/trekka_logo_app.png
    - assets/images/cafe.jpg
    - assets/images/museum.jpg
    - assets/images/noodle_street.jpg
    - assets/images/cafe_interior_1.jpg
    - assets/images/cafe_interior_2.jpg
    - assets/images/cafe_interior_3.jpg