name: trekka
description: A travel_preferences planning app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/trekka_logo.png
    - assets/images/trekka_logo_app.png
    - assets/images/cafe.jpg
    - assets/images/museum.jpg
    - assets/images/noodle_street.jpg
    - assets/images/cafe_interior_1.jpg
    - assets/images/cafe_interior_2.jpg
    - assets/images/cafe_interior_3.jpg