name: trekka
description: A travel_preferences planning app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0             # Gọi API
  flutter_bloc: ^9.1.1    # State Management
  equatable: ^2.0.7       # So sánh object
  get_it: ^9.2.0          # Dependency Injection
  dartz: ^0.10.1          # Functional programming
  go_router: ^17.0.0     # Điều hướng thông minh
  google_fonts: ^6.3.3    # Font chữ
  flutter_svg: ^2.2.3     # Hiển thị Logo SVG
  cupertino_icons: ^1.0.8 # Biểu tượng iOS
  shared_preferences: ^2.5.3 # Lưu trữ dữ liệu cục bộ
  flutter_native_splash: ^2.4.7
  intl: ^0.20.2
  url_launcher: ^6.3.2    # Mở links và maps
  easy_localization: ^3.0.7  # Đa ngôn ngữ
  chuck_interceptor: ^2.3.3  # HTTP Inspector - Thay thế Alice (Alice 0.4.1 lỗi build Android)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_native_splash:
  color: "#121E1E"
  image: "assets/images/trekka_logo_app.png"
  android_12:
    image: "assets/images/trekka_logo_app.png"
    color: "#121E1E"
    fullscreen: true
  ios: true


# Cấu hình cho flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/trekka_logo_app.png"
  image_path_ios: "assets/images/trekka_logo_app_ios.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#121E1E"
  adaptive_icon_foreground: "assets/images/trekka_logo_app.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
